### ISSUE TITLE
yarn install / yarn test does not work out of the box for typescript exercises

### ISSUE THREAD

**Issue by elmq0022** [exercism/typescript#1403]
node and yarn versions

```bash
two-fer$ node --version
v20.9.0
two-fer$ yarn --version
3.6.0
```
The instructions of yarn install and yarn test don't work out of the box.  I imagine there is some mismatch on package versions.  

This forum post seems to have a workable (albeit slightly annoying) work around, https://forum.exercism.org/t/issue-with-local-jest-type-definitions-yarn-3-and-jest/6867 

Basically it's:

```bash
yarn install
npm i --save-dev @types/jest
yarn install
yarn test
```

Here's my install and the error for reference.  

```bash
two-fer$ yarn install
➤ YN0000: ┌ Resolution step
➤ YN0032: │ fsevents@npm:2.3.3: Implicit dependencies on node-gyp are discouraged
➤ YN0061: │ @npmcli/move-file@npm:2.0.1 is deprecated: This functionality has been moved to @npmcli/fs
➤ YN0002: │ @exercism/typescript-two-fer@workspace:. doesn't provide @babel/core (p04199), requested by babel-jest
➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
➤ YN0000: └ Completed in 9s 534ms
➤ YN0000: ┌ Fetch step
➤ YN0013: │ yallist@npm:3.1.1 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ yallist@npm:4.0.0 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ yargs-parser@npm:21.1.1 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ yargs@npm:17.7.2 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ yocto-queue@npm:0.1.0 can't be found in the cache and will be fetched from the remote registry
➤ YN0000: └ Completed in 2s 399ms
➤ YN0000: ┌ Link step
➤ YN0000: │ ESM support for PnP uses the experimental loader API and is therefore experimental
➤ YN0007: │ core-js@npm:3.30.2 must be built because it never has been before or the last one failed
➤ YN0007: │ core-js@npm:3.33.1 must be built because it never has been before or the last one failed
➤ YN0000: └ Completed in 2s 766ms
➤ YN0000: Done with warnings in 14s 903ms

two-fer$ yarn test
Type Error: Cannot read properties of undefined (reading ~/two-fer/.pnp.cjs')
    at c4 (~/two-fer/.yarn/releases/yarn-3.6.0.cjs:390:12692)
    at a0e (~/two-fer/.yarn/releases/yarn-3.6.0.cjs:390:13173)
    at Object.mf (~/two-fer/.yarn/releases/yarn-3.6.0.cjs:390:13402)
    at ~/two-fer/.yarn/releases/yarn-3.6.0.cjs:694:4611
    at Object.Ta (~/two-fer/.yarn/releases/yarn-3.6.0.cjs:390:10714)
    at wl.findPackageLocation (~/two-fer/.yarn/releases/yarn-3.6.0.cjs:694:4566)
    at ~/two-fer/.yarn/releases/yarn-3.6.0.cjs:423:1264
    at Function.from (<anonymous>)
    at LB (~/two-fer/.yarn/releases/yarn-3.6.0.cjs:423:1008)
    at d9 (~/two-fer/.yarn/releases/yarn-3.6.0.cjs:423:1589)
```

**Comment by adamfeldman** [comment]
See also this forum reply from a maintainer: http://forum.exercism.org/t/issue-with-local-jest-type-definitions-yarn-3-and-jest/6867/17
